<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h2>Welcome, Adventurer!</h2>
<form action="/login" method="post">
    <label for="username">Username (your secret identity):</label><br>
    <input type="text" id="username" name="username" required><br><br>

    <label for="password">Password (the key to unlock your potential):</label><br>
    <input type="password" id="password" name="password" required><br><br>

    <input type="submit" value="Unleash the Power">
</form>
</body>
</html>